name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]
  push:
    paths:
      - config/west.yml
      - config/*.keymap
      - boards/**
      - build.yaml
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2